### ISSUE TITLE
Apply for Concurso INNOVAR

### ISSUE THREAD

**Issue by glpuga** [Ekumen-OS/beluga#164]
### Deadline for application

May 15th.

### Tasks

- [x] Fill the project application fom at https://www.innovar.mincyt.gob.ar/ (first draft)
- [x] Review project application form.
- [x] Fill team members information
  - DNI, address, phone, age, furthest university studies (undergraduate, graduate, posgraduate), university name, career title (e.g. Electronic Engineer)
- [x] Fill company information (Creativa77)
- [x] Generate some still images for the jury and the project catalog.
- [x] Generate videos for the jury to watch.
- [x] Load images and videos to form.

### Links

- https://www.innovar.mincyt.gob.ar/
- [Bases y Condiciones](https://www.innovar.mincyt.gob.ar/docs/INNO2023_bases-y-condiciones.pdf)
- [Instructivo](https://www.innovar.mincyt.gob.ar/docs/INNO2023_instructivo-web.pdf)
