### ISSUE TITLE
Make `beluga_amcl` a drop-in replacement of `nav2_amcl`

### ISSUE THREAD

**Issue by nahueespinosa** [Ekumen-OS/beluga#85]
## Description
This ticket is meant to track the progress in making a drop-in replacement of `nav2_amcl` in terms of interface and parameters.
Specific features and requirements will be best tracked in their own issues.

## Definition of done

Complete the implementation of the following list of parameters, services, publishers and subscribers:
- Parameters
  - ROS topics and frames
    - [x] `base_frame_id`
    - [x] `global_frame_id`
    - [x] `odom_frame_id`
    - [x] `scan_topic`
    - [x] `map_topic`
    - [x] `initial_pose_topic` (extra)
  - Initial pose (see #41)
    - [x] `set_initial_pose`
    - [x] `initial_pose`
    - <del>`save_pose_rate`</del>
    - [x] `always_reset_initial_pose`
    - [x] `first_map_only`
  - Publish map to odom transform (see #40)
    - [x] `tf_broadcast`
    - [x] `transform_tolerance`
  - Particle filter
    - [x] `max_particles`
    - [x] `min_particles`
    - [x] `pf_err`
    - [x] `pf_z`
    - [x] `recovery_alpha_fast`
    - [x] `recovery_alpha_slow`
    - [x] `spatial_resolution` (extra)
    - [x] `resample_interval` (see #57)
    - [x] `selective_resampling` (see #57)
  - Motion model
    - [x] `robot_model_type`
    - [x] `alpha1`
    - [x] `alpha2`
    - [x] `alpha3`
    - [x] `alpha4`
    - [x] `alpha5` (see #56)
    - [x] `update_min_a`
    - [x] `update_min_d`
  - Sensor model
    - [x] `laser_model_type`
    - [x] `laser_max_range`
    - [x] `laser_min_range`
    - [x] `max_beams` (see #84) 
    - [x] `sigma_hit`
    - [x] `z_hit`
    - [x] `z_rand`
  - Likelihood field model exclusive
    - [x] `laser_likelihood_max_dist`
    - [ ] `beam_skip_distance`
    - [ ] `beam_skip_error_threshold`
    - [ ] `beam_skip_threshold`
    - [ ] `do_beamskip` (see #187)
  - Beam model exclusive (see #54)
    - [x] `lambda_short`
    - [x] `z_max`
    - [x] `z_short`
- Services
  - [x] `reinitialize_global_localization`
  - [ ] `request_nomotion_update` (see #184)
- Publishers
  - [x] `pose`
  - [x] `particle_cloud` 
  - [x] `likelihood_field` (extra)
- Subscribers
  - [x] `map`
  - [x] `initial_pose`
  - [x] `scan`

**Comment by nahueespinosa** [comment]
With #196 documenting the current compatibility state between `beluga_amcl` and `nav2_amcl`, this ticket is no longer necessary.

#172, #184 and #187 describe the remaining work to be done to achieve full feature parity.
